name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_maps_flutter: ^2.0.10
  yandex_mapkit: ^4.0.2
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  permission_handler: ^10.1.0

flutter:
  uses-material-design: true
