services:
  medilink:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - postgres
    command: sh -c "npm run build && npm run migration:run && npm run start:prod"

  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:




