name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run deployment commands
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh root@45.89.65.109 'echo "Connected to server" && 
          cd MediLink/server && 
          echo "CD completed" &&
          git pull && 
          echo "Git pull completed" && 
          docker compose build && 
          echo "Docker compose build completed" && 
          docker compose up -d && 
          echo "Docker compose up completed"'
        shell: bash

