name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ HOST }}
        username: ${{ USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd MediLink/server
          git pull
          docker compose up -d --build


